version: '3'
services:
  postgres-server:
    container_name: postgres-server
    image: postgres:13
    restart: always
    volumes:
      - /home/nora/Programs/Data/postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
